# Используем официальный образ Node.js
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Собираем приложение с серверным рендерингом
RUN npm run build:ssr

# Открываем порт 4000
EXPOSE 4000

# Указываем команду для запуска приложения
CMD ["node", "dist/cv_2.0/server/main.js"]
