# Stage 1: Build the Angular app
FROM node:18 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Build the Angular app with SSR
RUN npm run build:ssr --localize

# Expose the port the app runs on
EXPOSE 4000

# Command to run the app using serve:ssr
CMD ["npm", "run", "serve:ssr"]
