FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Собираем приложение
RUN npm run build --prod

# Expose the port the app runs on
EXPOSE 3000

# Указываем команду для запуска приложения
CMD ["node", "dist/main"]