FROM node:20

WORKDIR /app

COPY package*.json ./
# Установите все зависимости включая devDependencies для сборки
RUN npm install --include=dev

COPY . .
RUN npm run build

# Установите только production зависимости для финального образа
RUN npm ci --only=production

EXPOSE 3000

CMD ["node", "dist/main.js"]