FROM node:20

WORKDIR /app

# Копируем package files
COPY package*.json ./

# Устанавливаем все зависимости
RUN npm install --include=dev

# Копируем исходный код
COPY . .

EXPOSE 3000

# Команда для development
CMD ["npm", "run", "start:dev"]